### ISSUE TITLE
Pitch and Roll in navigation.attitude key

### ISSUE THREAD

**Issue by GHBLoos** [GaryWSmith/xdr-parser-plugin#4]
Great plugin. Thanks for that. 

I have an XDR sentence for Pitch and Roll. In the SignalK specification the following key is specified for Roll and Pitch
```
/vessels/<RegExp>/navigation/attitude
Title: Attitude
Description: Vessel attitude: roll, pitch and yaw
Object value with properties
roll (rad)
pitch (rad)
yaw (rad)

```
This should result in
```
navigation.attitiude
{
  "roll": 0.00, 
  "pitch": 0.00,
  "yaw": 0.00
} 
```

Is that possible with the current plugin? Based upon the answer there is of course a second question.

**Comment by GaryWSmith** [comment]
If I understand your email correctly then the answer is yes. I think that I
cover this in the github documentation.

Username garywsmith

**Comment by GaryWSmith** [comment]
To be clear,  there yaw value in the object is instantiated to 0 and will
remain 0 unless a valid yaw value is found in the xdr message.

**Comment by GHBLoos** [comment]
Thanks for your reply.
I am not sure what I should put in the input fields. Currently I have:
Category: `angle`
units: `rad`
XDR Sensor identifier: `PTCH`
Math Expression: `(0.0174532925*x+0)`
Fixed decimal: `2`
Signalk Path: `navigation.attitude.pitch`

and

category: `angle`
units: `rad`
XDR Sensor identifier: `ROLL`
Math Expression: `(0.0174532925*x+0)`
Fixed decimal: `2`
Signalk Path: `navigation.attitude.roll`

But that doesn't give me
```
navigation.attitude
{
  "roll": 0.00, 
  "pitch": 0.00,
  "yaw": 0.00
} 
```

**Comment by GaryWSmith** [comment]
I'd have to go back and look at the documentation but for a quick answer
I've just checked my setup.

Descriptive sensor name = Pitch
Category = Angles
Units = Deg
XDR Sensor identifier = PTCH
Math expression = (x*pi/180)
Fixed decimal = 2
Signalk path = navigation.attitude

I see that there are a couple of differences compared with yours ...

The crucial settings are:
The exact XDR Sensor identifier
A valid math expression
A valid signalk path.

Hope this helps.

**Comment by GaryWSmith** [comment]
By the way, my example assumes that the XDR message contains degrees.

Signalk expects radians hence the math expression.

x is the value in the XDR message which must be transformed.

**Comment by GaryWSmith** [comment]
I think that you've highlighted a flaw in my logic. There isn't apparently
anything which links ROLL, PITCH or YAW to the appropriate properties of
the attitude object.

That is, they are probably hard coded on the sensor identifier.

Please let me know if my config example works for you.

**Comment by GaryWSmith** [comment]
I've just confirmed that I have hard coded the sensor identifier PTCH, ROLL
and YAW ...

So if your XDR message is different you'll have a problem.

Let me know.

**Comment by GHBLoos** [comment]
I am using a Airmar PB200. XDR(B) sentences can be found on page 100/101 of [this manual](https://www.airmar.com/uploads/installguide/PB200UserManual.pdf).

My XDR sentence is also in degrees. Our math expression is the same, although you wrote it down more nicely (I wasn't sure 'pi' would be recognized). 

I also have PTCH and ROLL as identifiers (I wrote PITCH, but it is PTCH).

Why are you writing DEG in units when you are sending RAD?

**Comment by GaryWSmith** [comment]
The fields are primarily about the incoming XDR sentences e.g. Deg.

The signalk protocol use pre-defined SI units so there is no need to
describe them.

The math expression is used to convert the potentially arbitrary incoming
units to SI units.

Did you notice the difference in our signalk path definition? Don't include
the ".roll" or ".pitch"

**Comment by GHBLoos** [comment]
Yes I noticed, and I changed that. It works flawless. Awesome. I think I just didn't expect that it would be managed in the code. Thanks!
